name: "Alex's Test Site"
favicon: null
layout_spectrum: 0.35686
typography_spectrum: 0.14058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25
  lightness: 0.5315881238784641
  saturation: 0.8412495171651244
  rhythmicContrast: 0.26485164393670857
purpose: []
